/** ESV's 66-book Protestant canon. No Scripture text is stored in this index. */
export type EsvBook = {
  readonly id: string;
  readonly name: string;
  readonly chapterCount: number;
  /** ESV numeric references encode book ordinal, chapter, and verse. */
  readonly ordinal: number;
};

// IDs match existing offline references, highlights, and notes.
export const esvBooks: readonly EsvBook[] = [
  { id: 'GEN', name: 'Genesis', chapterCount: 50, ordinal: 1 },
  { id: 'EXO', name: 'Exodus', chapterCount: 40, ordinal: 2 },
  { id: 'LEV', name: 'Leviticus', chapterCount: 27, ordinal: 3 },
  { id: 'NUM', name: 'Numbers', chapterCount: 36, ordinal: 4 },
  { id: 'DEU', name: 'Deuteronomy', chapterCount: 34, ordinal: 5 },
  { id: 'JOS', name: 'Joshua', chapterCount: 24, ordinal: 6 },
  { id: 'JDG', name: 'Judges', chapterCount: 21, ordinal: 7 },
  { id: 'RUT', name: 'Ruth', chapterCount: 4, ordinal: 8 },
  { id: '1SA', name: '1 Samuel', chapterCount: 31, ordinal: 9 },
  { id: '2SA', name: '2 Samuel', chapterCount: 24, ordinal: 10 },
  { id: '1KI', name: '1 Kings', chapterCount: 22, ordinal: 11 },
  { id: '2KI', name: '2 Kings', chapterCount: 25, ordinal: 12 },
  { id: '1CH', name: '1 Chronicles', chapterCount: 29, ordinal: 13 },
  { id: '2CH', name: '2 Chronicles', chapterCount: 36, ordinal: 14 },
  { id: 'EZR', name: 'Ezra', chapterCount: 10, ordinal: 15 },
  { id: 'NEH', name: 'Nehemiah', chapterCount: 13, ordinal: 16 },
  { id: 'EST', name: 'Esther', chapterCount: 10, ordinal: 17 },
  { id: 'JOB', name: 'Job', chapterCount: 42, ordinal: 18 },
  { id: 'PSA', name: 'Psalms', chapterCount: 150, ordinal: 19 },
  { id: 'PRO', name: 'Proverbs', chapterCount: 31, ordinal: 20 },
  { id: 'ECC', name: 'Ecclesiastes', chapterCount: 12, ordinal: 21 },
  { id: 'SOL', name: 'Song of Solomon', chapterCount: 8, ordinal: 22 },
  { id: 'ISA', name: 'Isaiah', chapterCount: 66, ordinal: 23 },
  { id: 'JER', name: 'Jeremiah', chapterCount: 52, ordinal: 24 },
  { id: 'LAM', name: 'Lamentations', chapterCount: 5, ordinal: 25 },
  { id: 'EZE', name: 'Ezekiel', chapterCount: 48, ordinal: 26 },
  { id: 'DAN', name: 'Daniel', chapterCount: 12, ordinal: 27 },
  { id: 'HOS', name: 'Hosea', chapterCount: 14, ordinal: 28 },
  { id: 'JOE', name: 'Joel', chapterCount: 3, ordinal: 29 },
  { id: 'AMO', name: 'Amos', chapterCount: 9, ordinal: 30 },
  { id: 'OBA', name: 'Obadiah', chapterCount: 1, ordinal: 31 },
  { id: 'JON', name: 'Jonah', chapterCount: 4, ordinal: 32 },
  { id: 'MIC', name: 'Micah', chapterCount: 7, ordinal: 33 },
  { id: 'NAH', name: 'Nahum', chapterCount: 3, ordinal: 34 },
  { id: 'HAB', name: 'Habakkuk', chapterCount: 3, ordinal: 35 },
  { id: 'ZEP', name: 'Zephaniah', chapterCount: 3, ordinal: 36 },
  { id: 'HAG', name: 'Haggai', chapterCount: 2, ordinal: 37 },
  { id: 'ZEC', name: 'Zechariah', chapterCount: 14, ordinal: 38 },
  { id: 'MAL', name: 'Malachi', chapterCount: 4, ordinal: 39 },
  { id: 'MAT', name: 'Matthew', chapterCount: 28, ordinal: 40 },
  { id: 'MAR', name: 'Mark', chapterCount: 16, ordinal: 41 },
  { id: 'LUK', name: 'Luke', chapterCount: 24, ordinal: 42 },
  { id: 'JOH', name: 'John', chapterCount: 21, ordinal: 43 },
  { id: 'ACT', name: 'Acts', chapterCount: 28, ordinal: 44 },
  { id: 'ROM', name: 'Romans', chapterCount: 16, ordinal: 45 },
  { id: '1CO', name: '1 Corinthians', chapterCount: 16, ordinal: 46 },
  { id: '2CO', name: '2 Corinthians', chapterCount: 13, ordinal: 47 },
  { id: 'GAL', name: 'Galatians', chapterCount: 6, ordinal: 48 },
  { id: 'EPH', name: 'Ephesians', chapterCount: 6, ordinal: 49 },
  { id: 'PHI', name: 'Philippians', chapterCount: 4, ordinal: 50 },
  { id: 'COL', name: 'Colossians', chapterCount: 4, ordinal: 51 },
  { id: '1TH', name: '1 Thessalonians', chapterCount: 5, ordinal: 52 },
  { id: '2TH', name: '2 Thessalonians', chapterCount: 3, ordinal: 53 },
  { id: '1TI', name: '1 Timothy', chapterCount: 6, ordinal: 54 },
  { id: '2TI', name: '2 Timothy', chapterCount: 4, ordinal: 55 },
  { id: 'TIT', name: 'Titus', chapterCount: 3, ordinal: 56 },
  { id: 'PHM', name: 'Philemon', chapterCount: 1, ordinal: 57 },
  { id: 'HEB', name: 'Hebrews', chapterCount: 13, ordinal: 58 },
  { id: 'JAM', name: 'James', chapterCount: 5, ordinal: 59 },
  { id: '1PE', name: '1 Peter', chapterCount: 5, ordinal: 60 },
  { id: '2PE', name: '2 Peter', chapterCount: 3, ordinal: 61 },
  { id: '1JO', name: '1 John', chapterCount: 5, ordinal: 62 },
  { id: '2JO', name: '2 John', chapterCount: 1, ordinal: 63 },
  { id: '3JO', name: '3 John', chapterCount: 1, ordinal: 64 },
  { id: 'JUD', name: 'Jude', chapterCount: 1, ordinal: 65 },
  { id: 'REV', name: 'Revelation', chapterCount: 22, ordinal: 66 },
];
