name: Create development builds
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  android_development_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: development
