insert into public.bible_versions (
  id,
  short_label,
  label,
  language,
  description,
  size_bytes,
  local_filename,
  storage_path,
  public_url,
  is_bundled,
  is_enabled,
  sort_order,
  checksum
)
values
  (
    'OEB',
    'OEB',
    'Open English Bible (US)',
    'English',
    'The Holy Bible, Open English Bible translation, U. S. spelling edition. Partial edition currently includes 44 books.',
    2002025,
    'oeb.json',
    'OEB.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/OEB.json',
    false,
    true,
    14,
    null
  ),
  (
    'MSB',
    'MSB',
    'Majority Standard Bible',
    'English',
    'The Holy Bible in English, Majority Standard Bible',
    4599444,
    'msb.json',
    'MSB.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/MSB.json',
    false,
    true,
    17,
    null
  ),
  (
    'WPB',
    'WPB',
    'World Portuguese Bible',
    'Portuguese',
    'The Holy Bible in Portuguese, Brazilian dialect, Bíblia Portuguesa Mundial translation',
    4799011,
    'wpb.json',
    'WPB.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/WPB.json',
    false,
    true,
    50,
    null
  ),
  (
    'FFHB',
    'FFHB',
    'French Free Holy Bible for the World',
    'French',
    'The Holy Bible in French, Sainte Bible Libre pour le monde translation, including the deuterocanonical books present in the source edition.',
    6094038,
    'ffhb.json',
    'FFHB.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/FFHB.json',
    false,
    true,
    51,
    null
  ),
  (
    'AVD',
    'AVD',
    'Arabic Van Dyck Bible',
    'Arabic',
    'Arabic Van Dyck translation of the Holy Bible',
    8147739,
    'arbvd.json',
    'ARBVD.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/ARBVD.json',
    false,
    true,
    52,
    null
  ),
  (
    'MHB',
    'MHB',
    'Modern Hebrew Bible',
    'Hebrew',
    'The Holy Bible in Modern Hebrew.',
    4439480,
    'mhb.json',
    'MHB.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/MHB.json',
    false,
    true,
    53,
    null
  ),
  (
    'TCGNT',
    'TCGNT',
    'Text-Critical Greek NT',
    'Ancient Greek',
    'Text-Critical Greek NT. New Testament only.',
    1860766,
    'tcgnt.json',
    'TCGNT.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/TCGNT.json',
    false,
    true,
    54,
    null
  ),
  (
    'SFBW',
    'SFBW',
    'Spanish Free Bible for the World',
    'Spanish',
    'The Holy Bible in Spanish, Santa Biblia libre para el mundo translation, including the deuterocanonical books present in the source edition.',
    5462093,
    'sfbw.json',
    'SFBW.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/SFBW.json',
    false,
    true,
    55,
    null
  )
on conflict (id) do update
set
  short_label = excluded.short_label,
  label = excluded.label,
  language = excluded.language,
  description = excluded.description,
  size_bytes = excluded.size_bytes,
  local_filename = excluded.local_filename,
  storage_path = excluded.storage_path,
  public_url = excluded.public_url,
  is_bundled = excluded.is_bundled,
  is_enabled = excluded.is_enabled,
  sort_order = excluded.sort_order,
  checksum = excluded.checksum;
