insert into public.bible_versions (
  id,
  short_label,
  label,
  language,
  description,
  size_bytes,
  local_filename,
  storage_path,
  public_url,
  is_bundled,
  is_enabled,
  checksum
)
values
  (
    'ASV',
    'ASV',
    'American Standard Version',
    'English',
    'American Standard Version. Download for offline reading.',
    4859356,
    'asv.json',
    'ASV.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/ASV.json',
    false,
    true,
    null
  ),
  (
    'ACV',
    'ACV',
    'A Conservative Version',
    'English',
    'A Conservative Version. Download for offline reading.',
    4800934,
    'acv.json',
    'ACV.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/ACV.json',
    false,
    true,
    null
  ),
  (
    'YLT',
    'YLT',
    'Young''s Literal Translation',
    'English',
    'Literal English translation. Download for offline reading.',
    4840198,
    'ylt.json',
    'YLT.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/YLT.json',
    false,
    true,
    null
  ),
  (
    'NHEB',
    'NHEB',
    'New Heart English Bible',
    'English',
    'New Heart English Bible. Download for offline reading.',
    4750793,
    'nheb.json',
    'NHEB.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/NHEB.json',
    false,
    true,
    null
  ),
  (
    'RWEBSTER',
    'RWeb',
    'Revised Webster Version',
    'English',
    'English revision of Webster Bible. Download for offline reading.',
    4832637,
    'rwebster.json',
    'RWEBSTER.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/RWEBSTER.json',
    false,
    true,
    null
  ),
  (
    'JPS',
    'JPS',
    'Jewish Publication Society Old Testament',
    'English',
    'Jewish Publication Society Old Testament. Old Testament only.',
    3726289,
    'jps.json',
    'JPS.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/JPS.json',
    false,
    true,
    null
  ),
  (
    'CUVL',
    'CUVl',
    'Chinese Union Version (Literary)',
    'Literary Chinese',
    'Literary Chinese Union Version.',
    3104010,
    'cuvl.json',
    'CUVL.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/CUVL.json',
    false,
    true,
    null
  ),
  (
    'RUSSYNODAL',
    'RUS',
    'Russian Synodal Bible',
    'Russian',
    'Russian Synodal text using Synodal versification.',
    6862415,
    'russynodal.json',
    'RUSSYNODAL.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/RUSSYNODAL.json',
    false,
    true,
    null
  ),
  (
    'KORRV',
    'KorRV',
    'Korean Revised Version',
    'Korean',
    'Korean Revised Version. Download for offline reading.',
    5138651,
    'korrv.json',
    'KORRV.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/KORRV.json',
    false,
    true,
    null
  ),
  (
    'RV1909',
    'RV1909',
    'Reina-Valera 1909',
    'Spanish',
    'The Holy Bible in Spanish, Reina Valera translation of 1909. Download for offline reading.',
    4645812,
    'rv1909.json',
    'RV1909.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/RV1909.json',
    false,
    true,
    null
  ),
  (
    'LSG1910',
    'LSG',
    'Louis Segond 1910',
    'French',
    'The Holy Bible in French, Louis Segond translation of 1910. Download for offline reading.',
    5023743,
    'lsg1910.json',
    'LSG1910.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/LSG1910.json',
    false,
    true,
    null
  ),
  (
    'LUTHER1912',
    'L1912',
    'Luther Bible 1912',
    'German',
    'The Holy Bible in German, Luther translation of 1912. Download for offline reading.',
    4802009,
    'luther1912.json',
    'LUTHER1912.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/LUTHER1912.json',
    false,
    true,
    null
  ),
  (
    'DRA',
    'DRA',
    'Douay-Rheims 1899',
    'English',
    'Douay-Rheims 1899 with the full deuterocanonical books included. Download for offline reading.',
    5462093,
    'dra.json',
    'DRA.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/DRA.json',
    false,
    true,
    null
  ),
  (
    'WEB',
    'WEB',
    'World English Bible',
    'English',
    'World English Bible with the deuterocanonical books included. Download for offline reading.',
    5813810,
    'web.json',
    'WEB.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/WEB.json',
    false,
    true,
    null
  ),
  (
    'HINCV',
    'HCV',
    'Hindi Contemporary Version',
    'Hindi',
    'Hindi Contemporary Version. CC BY-SA 4.0. Original work by Biblica, Inc.',
    11039186,
    'hincv.json',
    'HINCV.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/HINCV.json',
    false,
    true,
    null
  ),
  (
    'SWHCV',
    'KCV',
    'Kiswahili Contemporary Version',
    'Swahili',
    'Kiswahili Contemporary Version. CC BY-SA 4.0. Original work by Biblica, Inc.',
    4659636,
    'swhcv.json',
    'SWHCV.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/SWHCV.json',
    false,
    true,
    null
  ),
  (
    'LXXRP',
    'LXX+RP',
    'Greek Septuagint + RP NT',
    'Ancient Greek',
    'Composite Ancient Greek Bible Brenton Septuagint source and the Robinson-Pierpont 2018 Greek New Testament. Includes the deuterocanonical books present in the Brenton source edition.',
    9249377,
    'lxxrp.json',
    'LXXRP.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/LXXRP.json',
    false,
    true,
    null
  ),
  (
    'OEB',
    'OEB',
    'Open English Bible (US)',
    'English',
    'The Holy Bible, Open English Bible translation, U. S. spelling edition. Partial edition currently includes 44 books.',
    2002025,
    'oeb.json',
    'OEB.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/OEB.json',
    false,
    true,
    null
  ),
  (
    'MSB',
    'MSB',
    'Majority Standard Bible',
    'English',
    'The Holy Bible in English, Majority Standard Bible',
    4599444,
    'msb.json',
    'MSB.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/MSB.json',
    false,
    true,
    null
  ),
  (
    'WPB',
    'WPB',
    'World Portuguese Bible',
    'Portuguese',
    'The Holy Bible in Portuguese, Brazilian dialect, Bíblia Portuguesa Mundial translation',
    4799011,
    'wpb.json',
    'WPB.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/WPB.json',
    false,
    true,
    null
  ),
  (
    'FFHB',
    'FFHB',
    'French Free Holy Bible for the World',
    'French',
    'The Holy Bible in French, Sainte Bible Libre pour le monde translation, including the deuterocanonical books present in the source edition.',
    6094038,
    'ffhb.json',
    'FFHB.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/FFHB.json',
    false,
    true,
    null
  ),
  (
    'AVD',
    'AVD',
    'Arabic Van Dyck Bible',
    'Arabic',
    'Arabic Van Dyck translation of the Holy Bible',
    8147739,
    'arbvd.json',
    'ARBVD.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/ARBVD.json',
    false,
    true,
    null
  ),
  (
    'MHB',
    'MHB',
    'Modern Hebrew Bible',
    'Hebrew',
    'The Holy Bible in Modern Hebrew.',
    4439480,
    'mhb.json',
    'MHB.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/MHB.json',
    false,
    true,
    null
  ),
  (
    'TCGNT',
    'TCGNT',
    'Text-Critical Greek NT',
    'Ancient Greek',
    'Text-Critical Greek NT. New Testament only.',
    1860766,
    'tcgnt.json',
    'TCGNT.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/TCGNT.json',
    false,
    true,
    null
  ),
  (
    'SFBW',
    'SFBW',
    'Spanish Free Bible for the World',
    'Spanish',
    'The Holy Bible in Spanish, Santa Biblia libre para el mundo translation, including the deuterocanonical books present in the source edition.',
    5462093,
    'sfbw.json',
    'SFBW.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/SFBW.json',
    false,
    true,
    null
  )
on conflict (id) do update
set
  short_label = excluded.short_label,
  label = excluded.label,
  language = excluded.language,
  description = excluded.description,
  size_bytes = excluded.size_bytes,
  local_filename = excluded.local_filename,
  storage_path = excluded.storage_path,
  public_url = excluded.public_url,
  is_bundled = excluded.is_bundled,
  is_enabled = excluded.is_enabled,
  checksum = excluded.checksum;
