insert into public.bible_versions (
  id,
  short_label,
  label,
  language,
  description,
  size_bytes,
  local_filename,
  storage_path,
  public_url,
  is_bundled,
  is_enabled,
  sort_order,
  checksum
)
values
  (
    'RV1909',
    'RV1909',
    'Reina-Valera 1909',
    'Spanish',
    'The Holy Bible in Spanish, Reina Valera translation of 1909. Download for offline reading.',
    4645812,
    'rv1909.json',
    'RV1909.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/RV1909.json',
    false,
    true,
    45,
    null
  ),
  (
    'LSG1910',
    'LSG',
    'Louis Segond 1910',
    'French',
    'The Holy Bible in French, Louis Segond translation of 1910. Download for offline reading.',
    5023743,
    'lsg1910.json',
    'LSG1910.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/LSG1910.json',
    false,
    true,
    46,
    null
  ),
  (
    'LUTHER1912',
    'L1912',
    'Luther Bible 1912',
    'German',
    'The Holy Bible in German, Luther translation of 1912. Download for offline reading.',
    4802009,
    'luther1912.json',
    'LUTHER1912.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/LUTHER1912.json',
    false,
    true,
    47,
    null
  ),
  (
    'DRA',
    'DRA',
    'Douay-Rheims 1899',
    'English',
    'Douay-Rheims 1899 with the full deuterocanonical books included. Download for offline reading.',
    5462093,
    'dra.json',
    'DRA.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/DRA.json',
    false,
    true,
    18,
    null
  ),
  (
    'WEB',
    'WEB',
    'World English Bible',
    'English',
    'World English Bible with the deuterocanonical books included. Download for offline reading.',
    5813810,
    'web.json',
    'WEB.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/WEB.json',
    false,
    true,
    19,
    null
  ),
  (
    'HINCV',
    'HCV',
    'Hindi Contemporary Version',
    'Hindi',
    'Hindi Contemporary Version. CC BY-SA 4.0. Original work by Biblica, Inc.',
    11039186,
    'hincv.json',
    'HINCV.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/HINCV.json',
    false,
    true,
    56,
    null
  ),
  (
    'SWHCV',
    'KCV',
    'Kiswahili Contemporary Version',
    'Swahili',
    'Kiswahili Contemporary Version. CC BY-SA 4.0. Original work by Biblica, Inc.',
    4659636,
    'swhcv.json',
    'SWHCV.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/SWHCV.json',
    false,
    true,
    57,
    null
  )
on conflict (id) do update
set
  short_label = excluded.short_label,
  label = excluded.label,
  language = excluded.language,
  description = excluded.description,
  size_bytes = excluded.size_bytes,
  local_filename = excluded.local_filename,
  storage_path = excluded.storage_path,
  public_url = excluded.public_url,
  is_bundled = excluded.is_bundled,
  is_enabled = excluded.is_enabled,
  sort_order = excluded.sort_order,
  checksum = excluded.checksum;
