insert into public.bible_versions (
  id,
  short_label,
  label,
  language,
  description,
  size_bytes,
  local_filename,
  storage_path,
  public_url,
  is_bundled,
  is_enabled,
  sort_order,
  checksum
)
values
  (
    'ASV',
    'ASV',
    'American Standard Version',
    'English',
    'American Standard Version. Download for offline reading.',
    4859356,
    'asv.json',
    'ASV.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/ASV.json',
    false,
    true,
    10,
    null
  ),
  (
    'ACV',
    'ACV',
    'A Conservative Version',
    'English',
    'A Conservative Version. Download for offline reading.',
    4800934,
    'acv.json',
    'ACV.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/ACV.json',
    false,
    true,
    11,
    null
  ),
  (
    'YLT',
    'YLT',
    'Young''s Literal Translation',
    'English',
    'Literal English translation. Download for offline reading.',
    4840198,
    'ylt.json',
    'YLT.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/YLT.json',
    false,
    true,
    12,
    null
  ),
  (
    'NHEB',
    'NHEB',
    'New Heart English Bible',
    'English',
    'New Heart English Bible. Download for offline reading.',
    4750793,
    'nheb.json',
    'NHEB.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/NHEB.json',
    false,
    true,
    13,
    null
  ),
  (
    'RWEBSTER',
    'RWeb',
    'Revised Webster Version',
    'English',
    'English revision of Webster Bible. Download for offline reading.',
    4832637,
    'rwebster.json',
    'RWEBSTER.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/RWEBSTER.json',
    false,
    true,
    15,
    null
  ),
  (
    'JPS',
    'JPS',
    'Jewish Publication Society Old Testament',
    'English',
    'Jewish Publication Society Old Testament. Old Testament only.',
    3726289,
    'jps.json',
    'JPS.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/JPS.json',
    false,
    true,
    16,
    null
  ),
  (
    'CUVL',
    'CUVl',
    'Chinese Union Version (Literary)',
    'Literary Chinese',
    'Literary Chinese Union Version.',
    3104010,
    'cuvl.json',
    'CUVL.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/CUVL.json',
    false,
    true,
    42,
    null
  ),
  (
    'RUSSYNODAL',
    'RUS',
    'Russian Synodal Bible',
    'Russian',
    'Russian Synodal text using Synodal versification.',
    6862415,
    'russynodal.json',
    'RUSSYNODAL.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/RUSSYNODAL.json',
    false,
    true,
    60,
    null
  ),
  (
    'KORRV',
    'KorRV',
    'Korean Revised Version',
    'Korean',
    'Korean Revised Version. Download for offline reading.',
    5138651,
    'korrv.json',
    'KORRV.json',
    'https://ujdyhgasuwikfvldhxnb.supabase.co/storage/v1/object/public/bible_versions/KORRV.json',
    false,
    true,
    61,
    null
  )
on conflict (id) do update
set
  short_label = excluded.short_label,
  label = excluded.label,
  language = excluded.language,
  description = excluded.description,
  size_bytes = excluded.size_bytes,
  local_filename = excluded.local_filename,
  storage_path = excluded.storage_path,
  public_url = excluded.public_url,
  is_bundled = excluded.is_bundled,
  is_enabled = excluded.is_enabled,
  sort_order = excluded.sort_order,
  checksum = excluded.checksum;
