name: EASBuild and Submit Android

on:
  push:
    tags:
      - '*'

jobs:
  build_android:
    runs-on: ubuntu-latest
    env:
      EAS_PROFILE: beta

    steps:
      - name: 🏗️ Checkout repo
        uses: actions/checkout@v3

      - name: 🏗️ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 🏗️ Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🔖 Get app version
        run: echo "APP_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: 🏗️ Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android AAB
        run: eas build --platform android --profile $EAS_PROFILE --non-interactive --wait

      - name: Submit to Google Play
        run: eas submit --platform android --latest --non-interactive

      - name: GitHub Release Description
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ env.APP_VERSION }}
          body: |
            iOS Beta Build (TestFlight)
            - [Install via TestFlight](https://testflight.apple.com/join/j6Qs882p)

            Android Beta Build
            - [Install via Google Play Testing](https://play.google.com/apps/testing/life.thingsabove.app)

          generate_release_notes: true
          draft: false
          prerelease: false
